=== ritafermad/XML-Esquemas/ejercicio 2/sch_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="DatosClase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="alumno" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="nota">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="0"/>
              <xs:maxInclusive value="10"/>
              <xs:fractionDigits value="2"/>
            </xs:restriction>
          </xs:simpleType>
          </xs:element>
        <xs:element name="edad" type="xs:string" minOccurs="0"/>
        <xs:element name="comentario" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="dni" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ritafermad/XML-Esquemas/ejercicio 2/ej 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<DatosClase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Lenguajes%20de%20Marcas/Git/XML-Esquemas/ejercicio%202/sch_2.xsd">
<alumno dni="99887766X" >
<nombre>Dario</nombre>
<apellidos>Fernández Álvarez</apellidos>
<nota>3.50</nota>
<edad>45</edad>
<comentario>Necesita mejorar</comentario>
</alumno>
<alumno dni="11223344A">
<nombre>Luis</nombre>
<apellidos>Álvarez García</apellidos>
<nota>6.75</nota>
<edad>80</edad>
<comentario>Copió de Darío y Pilar</comentario>
</alumno>
<alumno dni="556677Z">
<nombre>Pilar</nombre>
<apellidos>Rodríguez Menéndez</apellidos>
<nota>8.25</nota>
<comentario>Progresa adecuadamente</comentario>
</alumno>
<alumno dni="66554433T">
<nombre>Alfredo</nombre>
<apellidos>Martínez González</apellidos>
<nota>0</nota>
<edad>42</edad>
<comentario>Estudió en universidad de Oviedo</comentario>
</alumno>
</DatosClase>
