=== ritafermad/XML-Esquemas/ejercicio 1/ej_esq_6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="musicos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name ="musico" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name = "nombre" type = "xs:string"/>
              <xs:element name = "fechaNacimiento" type = "xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
          </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ritafermad/XML-Esquemas/ejercicio 1/e_1_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<musicos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Lenguajes%20de%20Marcas/Git/XML-Esquemas/ejercicio%201/ej_esq_6.xsd">
  <musico>
    <nombre>Antonio Vivaldi</nombre>
    <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
  </musico>
  <musico>
    <nombre>Johann Sebastian Bach</nombre>
    <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
  </musico>
  <musico>
    <nombre>John Lennon</nombre>
  </musico>
</musicos>
