=== ritafermad/XML-Esquemas/ejercicio 1/ej_esq_10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="albumesMortadelo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="album" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="album">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="fecha" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:gYear">
        <xs:enumeration value="1969"/>
        <xs:enumeration value="1970"/>
        <xs:enumeration value="1971"/>
        <xs:enumeration value="1972"/>
        <xs:enumeration value="1973"/>
        <xs:enumeration value="1974"/>
      </xs:restriction>
      </xs:simpleType>
      </xs:attribute>
      </xs:complexType>
      </xs:element>
      </xs:schema>

=== ritafermad/XML-Esquemas/ejercicio 1/e_1_10.xml
<?xml version="1.0" encoding="UTF-8"?>
<albumesMortadelo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Lenguajes%20de%20Marcas/Git/XML-Esquemas/ejercicio%201/ej_esq_10.xsd">
  <album fecha="1969">
    <nombre>El sulfato atómico</nombre>
  </album>
  <album fecha="1971">
    <nombre>La caja de diez cerrojos</nombre>
  </album>
  <album fecha="1973">
    <nombre>El otro yo del profesor Bacterio</nombre>
  </album>
  <album fecha="1974">
    <nombre>Los cacharros majaretas</nombre>
  </album>
</albumesMortadelo>
