=== ritafermad/XML-Esquemas/ejercicio 1_1/sch-7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="contabilidad">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="apunte" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="apunte">
    <xs:complexType>
      <xs:sequence>
        <xs:choice> <!-- Uso de CHOICE porque no lleva orden-->
        <xs:element name="gasto"> <!-- Los 2 primeros son ELEMENTOS VACÍOS-->
                    <xs:complexType />
        </xs:element>
        <xs:element name="ingreso">
                    <xs:complexType />
        </xs:element>
        </xs:choice>
        <xs:element name="fecha" type="xs:string"/>
        <xs:element name="cantidad">
          <xs:simpleType>
            <xs:restriction base="xs:decimal"> <!-- restricciones MONEDA y CANTIDAD-->
            <xs:fractionDigits value="2"/>
            </xs:restriction>  
          </xs:simpleType>
          </xs:element>
        <xs:element name="moneda">
        <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="euro" />
          <xs:enumeration value="dolar"/>    
        </xs:restriction>
        </xs:simpleType>
        </xs:element>
        <xs:element name="concepto" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
        </xs:schema>

=== ritafermad/XML-Esquemas/ejercicio 1_1/7_contabilidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<contabilidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Lenguajes%20de%20Marcas/Git/XML-Esquemas/ejercicio%201_1/sch-7.xsd">
  <apunte>
    <ingreso/>
    <fecha>24 de febrero de 2011</fecha>
    <cantidad>1800.00</cantidad>
    <moneda>euro</moneda>
    <concepto>Salario</concepto>
  </apunte>
  <apunte>
    <gasto/>
    <fecha>28 de febrero de 2011</fecha>
    <cantidad>74.25</cantidad>
    <moneda>euro</moneda>
    <concepto>Recibo luz</concepto>
  </apunte>
</contabilidad>
